language: node_js

node_js:
  - "6.9.1"
  - "6.1"
  - "6"
  
services:
  - rack
  
before_script:
  - java -jar selenium-server-standalone-2.53.1.jar -port 4444 > /dev/null &
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"



