language: node_js

node_js:
  - "6.9.1"
  - "6.1"
  - "6"
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rackup private_pub.ru -s thin -E production &
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc


